zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: null # Or set a list of glob patterns, e.g. ["2026/survey/**","2026/reading-group/**"]

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  generation_kwargs:
    model: google/gemini-3.5-flash

source:
  arxiv:
    category: ["cs.AI","cs.CV","cs.LG","cs.CL","cs.CR"]

executor:
  delivery: both
  debug: ${oc.env:DEBUG,null}
  source: ['arxiv']

email:
  sender: ${oc.env:SENDER}
  receiver: turkey888appleid@gmail.com
  smtp_server: smtp.gmail.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}
