name: Daily arXiv digest
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Run script
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          SENDER: ${{ secrets.SENDER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          CUSTOM_CONFIG: ${{ vars.CUSTOM_CONFIG }}
        run: |
          printf "%b\n" "$CUSTOM_CONFIG" > config/custom.yaml
          echo "Use custom config: "
          cat config/custom.yaml
          uv run src/zotero_arxiv_daily/main.py

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-report
          path: report.md
          retention-days: 30
          if-no-files-found: ignore
